version: '3'
services:
  scrapy:
    build:
      context: scrapy/.    
    working_dir: /scrapy/scrapy_pj
    volumes:
      - ./scrapy/:/scrapy/
      - ./scrapy/cron:/var/spool/cron/crontabs/root
    links:
      - mongo
    environment:
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - MATTERMOST_WEBHOOK=${MATTERMOST_WEBHOOK}
      - TZ=Asia/Tokyo
  mongo:
    image: mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data/db:/data/db
    environment:
      - TZ=Asia/Tokyo
  node:
    build:
      context: ./node
    volumes:
      - ./node:/root/node
      - /root/node/app/node_modules/
      - /root/node/app/client/node_modules/
    ports:
      - 9000:2999
      - 9001:3000
    links:
      - mongo




