version: '3'
services:
  scrapy:
    build:
      context: scrapy/.    
      args:
        http_proxy: ${PROXY}
        https_proxy: ${PROXY}
        HTTP_PROXY: ${PROXY}
        HTTPS_PROXY: ${PROXY}
    working_dir: /scrapy/scrapy_pj
    volumes:
      - ./scrapy/:/scrapy/
      - ./scrapy/cron:/var/spool/cron/crontabs/root
    links:
      - mongo
    environment:
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - MATTERMOST_WEBHOOK=${MATTERMOST_WEBHOOK}
      - http_proxy=${PROXY}
      - https_proxy=${PROXY}
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
      - no_proxy=${NOPROXY}
      - TZ=Asia/Tokyo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    volumes:
      - ./mongo/data/db:/data/db
  node:
    build:
      context: ./node
      args:
        http_proxy: ${PROXY}
        https_proxy: ${PROXY}
        HTTP_PROXY: ${PROXY}
        HTTPS_PROXY: ${PROXY}
    volumes:
      - ./node:/root/node
      - /root/node/app/node_modules/
      - /root/node/app/client/node_modules/
    ports:
      - 9000:2999
      - 9001:3000
    links:
      - mongo
    environment:
      - http_proxy=${PROXY}
      - https_proxy=${PROXY}
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
      - no_proxy=localhost,127.0.0.1,mongo



