version: '3'
services:
  scrapy:
    restart: always
    build:
      context: scrapy/.    
      args:
        http_proxy: ${PROXY}
        https_proxy: ${PROXY}
        HTTP_PROXY: ${PROXY}
        HTTPS_PROXY: ${PROXY}
    environment:
      - http_proxy=${PROXY}
      - https_proxy=${PROXY}
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./scrapy/:/scrapy/
    links:
      - mongo
  mongo:
    restart: always
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/data/db:/data/db

  node:
    build:
      context: ./node
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
        no_proxy: localhost,fess
    volumes:
      - ./node:/root/node
      - /root/node/app/node_modules/
      - /root/node/app/client/node_modules/
    ports:
      - 9000:2999
      - 9001:3000
    links:
      - mongo




